name: Deploy LanGuard-CVE-Update Lambda

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lambda/lambda_function.py'
      - '.github/workflows/lambda/lambda-deploy.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 aws-sam-cli
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Create deployment package
        run: |
          mkdir -p lambda_package
          cp .github/workflows/lambda/lambda_function.py lambda_package/lambda_function.py
          cd lambda_package
          pip install boto3 -t .
          zip -r ../lambda_deployment_package.zip .
          cd ..
          
      - name: Deploy Lambda function
        run: |
          # Check if Lambda function exists
          if aws lambda get-function --function-name LanGuard-CVE-Update &> /dev/null; then
            # Update existing function
            aws lambda update-function-code \
              --function-name LanGuard-CVE-Update \
              --zip-file fileb://lambda_deployment_package.zip
          else
            # Create new function
            aws lambda create-function \
              --function-name LanGuard-CVE-Update \
              --runtime python3.10 \
              --handler lambda_function.lambda_handler \
              --role ${{ secrets.LAMBDA_EXECUTION_ROLE }} \
              --zip-file fileb://lambda_deployment_package.zip \
              --timeout 60 \
              --memory-size 256
          fi
          