name: CVE Monitor

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-cve-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/CVEProject/cvelistV5.git
          git fetch upstream
          
      - name: Check for delta.json changes
        id: check_changes
        run: |
          changes=$(git diff upstream/main -- cves/delta.json)
          if [ ! -z "$changes" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            git show upstream/main:cves/delta.json > delta.json
          else
            echo "No changes detected in delta.json"
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          
      # - name: Process CVE updates
      #   if: steps.check_changes.outputs.changes == 'true'
      #   run: python process_cve_updates.py
      #   env:
      #     CVE_PROCESSING_ENDPOINT: ${{ secrets.CVE_PROCESSING_ENDPOINT }}
      #     API_KEY: ${{ secrets.API_KEY }}
